version: '2'
services:
  nginx:
    image: nginx:alpine
    container_name: bt-challenge_nginx
    links:
      - php
    volumes:
      - ./app:/var/www/html:ro
      - ./docker/nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 443:443
  php:
    build: ./docker/php-81
    container_name: bt-challenge_php
    volumes:
      - ./app:/var/www/html
    depends_on:
      - db
    links:
      - db
  db:
    image: mariadb:latest
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123qwe
    ports:
      - 3306:3306
  rabbitmq:
    image: rabbitmq:latest
    container_name: bt-challenge_rabbitmq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
  adminer:
    image: adminer
    ports:
      - 8080:8080
  memcached:
    image: memcached:1.4
    ports:
      - 11211:11211
volumes:
  db-data:
    driver: local
