<div class="col-sm">
<?php echo $this->flashMessenger()->renderCurrent('error', ['alert', 'alert-dismissible', 'alert-danger']); ?>
    
    <?php echo $this->form()->openTag($form); ?>

    <div class="form-group">
        <?php echo $this->formRow($form->get('token')) ?>
    </div>

    <div class="form-group">
        <button type="submit" class="btn btn-primary btn-sm">Submit</button>
        <a href="/otp?resend=true" class="btn btn-primary btn-sm">Resend Token</a>
    </div>

    <?php echo $this->form()->closeTag(); ?>
</div>